title: Well Architected Lab for Partners 2022
description: >-
  Designed by a group of GPS Tech Team members.
  Ask your local GPS team to run this lab with coaches.
github_username:  Microsoft
markdown: GFM
theme: jekyll-theme-cayman
