title: Well Architected Lab for Partners 2022
description: >-
  Designed by some GPS CSA Team members.
  Ask your local GPS team to run this lab with coaches.
github_username:  Microsoft
markdown: GFM
theme: jekyll-theme-cayman
